# Generated by Django 6.0.6 on 2026-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
